apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "coolservice.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "coolservice.fullname" . }}
    name: {{ include "coolservice.fullname" . }}-config
    version: {{ .Values.version }}
    {{- if .Values.commonLabels }}
      {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
data:
  config.yaml: |-
    {{- toYaml .Values.config | nindent 4 }}
  {{ if .Values.image.filebeat.enabled }}
  filebeat.yaml: |-
    {{- toYaml .Values.filebeat | nindent 4 }}
  {{ end }}
