apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opa.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "opa.fullname" . }}
    name: {{ include "opa.fullname" . }}-config
    version: {{ .Values.version }}
    {{- if .Values.commonLabels }}
      {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
data:
  swisscom.rego:
    {{- toYaml .Values.config | nindent 4 }}
