apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opa.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "opa.fullname" . }}
    name: {{ include "opa.fullname" . }}
    version: {{ .Values.version }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "opa.fullname" . }}
  {{- if .Values.rollingStrategy }}
  strategy:
    {{- toYaml .Values.rollingStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "opa.fullname" . }}
        name: {{ include "opa.fullname" . }}
        version: {{ .Values.version }}
        {{- if .Values.commonLabels }}
{{- .Values.commonLabels | toYaml | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: opa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
#           command:
# {{ toYaml .Values.image.opa.command | indent 12 }}
          args:
{{ toYaml .Values.image.opa.args | indent 12 }}
          {{- with .Values.image.opa.resources }}
          resources:
{{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.image.opa.ports }}
          ports:
{{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
{{ toYaml .Values.image.opa.volumeMounts | indent 12 }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      restartPolicy: {{ .Values.restartPolicy }}
      volumes:
        - name: {{ include "opa.fullname" . }}-config
          configMap:
            defaultMode: 420
            name: {{ include "opa.fullname" . }}-config