apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "opa.fullname" . }}
    name: {{ include "opa.fullname" . }}
    version: {{ .Values.version }}
spec:
  selector:
    app: {{ include "opa.fullname" . }}
  ports:
    - name: {{ .Values.service.opa.name }}
      protocol: {{ .Values.service.opa.protocol }}
      port: {{ .Values.service.opa.port }}
      targetPort: {{ .Values.service.opa.targetPort }}
  type: NodePort